name: Build APP Android

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:

  # Creating Android applications from Ubuntu 22.04
  ubuntu_22_build:
    name: Ubuntu 22.04
    runs-on: ubuntu-22.04
    env:
      ANDROID_NDK_HOME: /home/runner/Android/Sdk/ndk/21.4.7075529
      ANDROID_HOME: /home/runner/Android/Sdk
      
    steps:

      # This action checks-out your repository.
      - uses: actions/checkout@v4

      # Install Node.JS 16
      - name: Install Node.JS 14
        uses: actions/setup-node@v4
        with:
          node-version: 14
          
      # Install Java 11
      - name: Install Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11.0.24+8'
      
      # Download Dependences Node.JS
      - name: Download Dependences Node.JS
        run: |
          yarn add jetifier
          yarn add querystring
          yarn install
          sed -i 's/md4/md5/g' node_modules/metro-cache/src/stableHash.js
          cat node_modules/metro-cache/src/stableHash.js
          yarn postinstall

      - name: Dependencies
        run: | 
            cd node_modules/turtlecoin-utils
            echo '{"coinUnitPlaces":6,"addressPrefix":78,"keccakIterations":1,"defaultNetworkFee":10000,"fusionMinInputCount":12,"fusionMinInOutCountRatio":4,"mmMiningBlockVersion":2,"maximumOutputAmount":100000000000000,"maximumOutputsPerTransaction":210,"maximumExtraSize":1024,"activateFeePerByteTransactions":true,"feePerByte": 800,"feePerByteChunkSize":256}' > config.json
            cd ../../ 
            cd node_modules/turtlecoin-wallet-backend/dist/lib
            echo '"use strict";Object.defineProperty(exports,"__esModule",{value:!0});const MixinLimits_1=require("./MixinLimits"),version=require("../../package.json").version;class Config{constructor(){this.decimalPlaces=6,this.addressPrefix=78,this.requestTimeout=1e4,this.blockTargetTime=120,this.syncThreadInterval=10,this.daemonUpdateInterval=1e4,this.lockedTransactionsCheckInterval=3e4,this.blocksPerTick=1,this.ticker="BTN",this.scanCoinbaseTransactions=!0,this.minimumFee=1e4,this.feePerByteChunkSize=256,this.minimumFeePerByte=204800/this.feePerByteChunkSize,this.mixinLimits=new MixinLimits_1.MixinLimits([new MixinLimits_1.MixinLimit(44e4,0,100,3),new MixinLimits_1.MixinLimit(62e4,2,7,7),new MixinLimits_1.MixinLimit(712160,1,3,3),],3),this.standardAddressLength=95,this.integratedAddressLength=183,this.underivePublicKey=void 0,this.derivePublicKey=void 0,this.deriveSecretKey=void 0,this.generateKeyImage=void 0,this.secretKeyToPublicKey=void 0,this.cnFastHash=void 0,this.generateRingSignatures=void 0,this.checkRingSignatures=void 0,this.generateKeyDerivation=void 0,this.blockStoreMemoryLimit=52428800,this.blocksPerDaemonRequest=100,this.maxLastFetchedBlockInterval=180,this.maxLastUpdatedNetworkHeightInterval=180,this.maxLastUpdatedLocalHeightInterval=180,this.customUserAgentString=`${this.ticker.toLowerCase()}-wallet-backend-${version}`,this.customRequestOptions={}}}function MergeConfig(i,e=new Config){let t=Object.create(Object.getPrototypeOf(e),Object.getOwnPropertyDescriptors(e));if(!i)return t;for(let[s,n]of Object.entries(i))t[s]=n;return t}exports.Config=Config,exports.MergeConfig=MergeConfig;' > Config.js
            cd ../../../../     

      # Download Command Line Tools SDK
      - name: Download Command Line Tools SDK
        run: |  
          cd $HOME
          wget https://dl.google.com/android/repository/commandlinetools-linux-6200805_latest.zip

      # Create Directory and Decompress - Command Line Tools SDK
      - name: Create Directory and Decompress - Command Line Tools SDK
        run: |    
          cd $HOME && mkdir -p Android/Sdk
          unzip commandlinetools-linux-6200805_latest.zip -d $HOME/Android/Sdk
          
      # Setup Android SDK        
      - name: Setup Android SDK
        run: |
            chmod 777 $HOME/Android/Sdk/tools/bin/*
            /home/runner/Android/Sdk/tools/bin/sdkmanager --list --include_obsolete --sdk_root=$ANDROID_HOME
            yes | /home/runner/Android/Sdk/tools/bin/sdkmanager "platform-tools" "cmdline-tools;latest" "ndk;21.4.7075529" "platforms;android-29" "build-tools;29.0.2" --sdk_root=$ANDROID_HOME --include_obsolete

      # Building APK APP      
      - name: Building APK APP
        run: |
           chmod 777 android/* && chmod 777 android/*/* && chmod 777 android/*/*/*
           export NODE_OPTIONS=--openssl-legacy-provider && sudo yarn deploy-android --reset-cache

      # Upload to GH Actions Artifacts
      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: ./android/app/build/outputs/apk/release/ 
